export const MenuIconsMobile = {
  NONE: '',
  DASHBOARD: 'view-dashboard',
  MAP: 'map',
  BOOK: 'book-open',
  FOLDER: 'folder',
  PANEL: 'desktop-mac',
  GRADUATION: 'school',
  USERS: 'account-group',
  MESSAGE: 'message',
  COMPASS: 'compass',
  LIBRARY: 'bookshelf',
  PALETTE: 'palette',
  TEACHER: 'human-male-board',
  CALENDAR: 'calendar-range',
  AWARD: 'trophy-award',
  SHIELD: 'shield-check',
  ROUTE: 'map-marker-path',
} as const;
