export const MenuIconsWeb = {
  none: '',
  layoutDashboard: 'lucide-layout-dashboard',
  map: 'lucide-map',
  bookOpen: 'lucide-book-open',
  folder: 'lucide-folder',
  panelTop: 'lucide-panel-top',
  graduationCap: 'lucide-graduation-cap',
  users: 'lucide-users',
  messageCircle: 'lucide-message-circle',
  compass: 'lucide-compass',
  library: 'lucide-library',
  palette: 'lucide-palette',
  presentation: 'lucide-presentation',
  calendarRange: 'lucide-calendar-range',
  award: 'lucide-award',
  shieldCheck: 'lucide-shield-check',
  route: 'lucide-route',
} as const;
