services:
  postgres:
    image: postgres:15
    container_name: gupjob-postgres
    environment:
      POSTGRES_USER: gupjob
      POSTGRES_PASSWORD: gupjob_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.all.databases.sql:/docker-entrypoint-initdb.d/01-init-databases.sql
      - ./seed.auth.sql:/docker-entrypoint-initdb.d/02-seed-auth.sql
      - ./seed.mentor.sql:/docker-entrypoint-initdb.d/03-seed-mentor.sql
      - ./seed.admin.sql:/docker-entrypoint-initdb.d/04-seed-admin.sql
      - ./seed.user.sql:/docker-entrypoint-initdb.d/05-seed-user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gupjob"]
      interval: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: gupjob-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: gupjob-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: