export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NO_TOKEN: 'NO_TOKEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  // Roadmap
  ROADMAP_NOT_FOUND: 'ROADMAP_NOT_FOUND',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',

  // Roadmap v2 — organisation & catalog
  DEPARTMENT_HAS_MAJORS: 'DEPARTMENT_HAS_MAJORS',
  DEPARTMENT_HAS_LECTURERS: 'DEPARTMENT_HAS_LECTURERS',
  MAJOR_HAS_PUBLISHED_CURRICULUM: 'MAJOR_HAS_PUBLISHED_CURRICULUM',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  COURSE_IN_USE: 'COURSE_IN_USE',
  COURSE_HAS_RESULTS: 'COURSE_HAS_RESULTS',
  COURSE_OFFERING_EXISTS: 'COURSE_OFFERING_EXISTS',
  LECTURER_IN_USE: 'LECTURER_IN_USE',

  // Roadmap v2 — curriculum lifecycle & canvas
  ROADMAP_VERSION_IMMUTABLE: 'ROADMAP_VERSION_IMMUTABLE',
  ROADMAP_DRAFT_EXISTS: 'ROADMAP_DRAFT_EXISTS',
  CURRICULUM_YEAR_ALREADY_PUBLISHED: 'CURRICULUM_YEAR_ALREADY_PUBLISHED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  PUBLISH_VALIDATION_FAILED: 'PUBLISH_VALIDATION_FAILED',
  PUBLISH_WARNINGS_NOT_ACKNOWLEDGED: 'PUBLISH_WARNINGS_NOT_ACKNOWLEDGED',
  CYCLE_DETECTED: 'CYCLE_DETECTED',
  INVALID_GRADE_SCALE: 'INVALID_GRADE_SCALE',

  // Roadmap v2 — student roadmap
  ALREADY_CLONED: 'ALREADY_CLONED',
  REVISION_CONFLICT: 'REVISION_CONFLICT',
  DUPLICATE_COURSE_IN_PLAN: 'DUPLICATE_COURSE_IN_PLAN',
  NODE_HAS_RESULT: 'NODE_HAS_RESULT',
  BASE_ITEM_NOT_REMOVABLE: 'BASE_ITEM_NOT_REMOVABLE',
  TERM_LIMIT_EXCEEDED: 'TERM_LIMIT_EXCEEDED',
  TERM_NOT_EMPTY: 'TERM_NOT_EMPTY',
  INVALID_WEIGHTS: 'INVALID_WEIGHTS',
  INVALID_SCORE: 'INVALID_SCORE',
  DUPLICATE_EDGE: 'DUPLICATE_EDGE',
  INVALID_SLOT_COURSE: 'INVALID_SLOT_COURSE',
  NODE_NOT_IN_TERM: 'NODE_NOT_IN_TERM',
  INVALID_OPERATION: 'INVALID_OPERATION',

  // Roadmap v2 — comments
  COMMENT_RATE_LIMITED: 'COMMENT_RATE_LIMITED',
  COMMENT_NOT_EDITABLE: 'COMMENT_NOT_EDITABLE',
  ALREADY_REPORTED: 'ALREADY_REPORTED',
  MODERATION_REASON_REQUIRED: 'MODERATION_REASON_REQUIRED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Service
  SERVICE_ERROR: 'SERVICE_ERROR',
  ROADMAP_SERVICE_ERROR: 'ROADMAP_SERVICE_ERROR',
  USER_SERVICE_ERROR: 'USER_SERVICE_ERROR',
  AUTH_SERVICE_ERROR: 'AUTH_SERVICE_ERROR',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
