// gateway/src/common/constants/error-codes.ts

export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NO_TOKEN: 'NO_TOKEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  // Roadmap
  ROADMAP_NOT_FOUND: 'ROADMAP_NOT_FOUND',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Service
  SERVICE_ERROR: 'SERVICE_ERROR',
  ADMIN_SERVICE_ERROR: 'ADMIN_SERVICE_ERROR',
  USER_SERVICE_ERROR: 'USER_SERVICE_ERROR',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
};