import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEnum, IsInt, IsNumber, IsOptional, IsString, IsUUID, Max, MaxLength, Min } from 'class-validator';
import { Type } from 'class-transformer';
import { AppConstant, EntityConstant } from '@iuroadmap/shared';
import { CustomTermKindEnum, RelationTypeEnum, TermInYearEnum } from '../../../../common/enums';

export enum RoadmapChangeOpType {
  MOVE_NODE = 'MOVE_NODE',
  ADD_NODE = 'ADD_NODE',
  REMOVE_NODE = 'REMOVE_NODE',
  FILL_SLOT = 'FILL_SLOT',
  CLEAR_SLOT = 'CLEAR_SLOT',
  RESET_NODE = 'RESET_NODE',
  ADD_EDGE = 'ADD_EDGE',
  REMOVE_EDGE = 'REMOVE_EDGE',
  ADD_TERM = 'ADD_TERM',
  MOVE_TERM = 'MOVE_TERM',
  UPDATE_TERM = 'UPDATE_TERM',
  REMOVE_TERM = 'REMOVE_TERM',
}

/**
 * One change of a batch (design §6.4). Fields used depend on `op`; the service checks them.
 * New keys (ADD_NODE / ADD_EDGE / ADD_TERM) are uuid v4 generated by the client so a later op of
 * the same batch can reference them (e.g. ADD_TERM then MOVE_NODE into it).
 * Curriculum items cannot be removed (BR-LRN-08): REMOVE_* only applies to items the learner added.
 */
export class RoadmapChangeOpRequest {
  @ApiProperty({ enum: RoadmapChangeOpType, enumName: 'RoadmapChangeOpType' })
  @IsEnum(RoadmapChangeOpType)
  op!: RoadmapChangeOpType;

  @ApiPropertyOptional({ format: 'uuid', description: 'MOVE_NODE, ADD_NODE (new key), REMOVE_NODE, FILL_SLOT, CLEAR_SLOT, RESET_NODE' })
  @IsUUID('4')
  @IsOptional()
  nodeKey?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'MOVE_NODE / ADD_NODE target term; ADD_TERM (new key), MOVE_TERM, UPDATE_TERM, REMOVE_TERM' })
  @IsUUID('4')
  @IsOptional()
  termKey?: string;

  @ApiPropertyOptional({ description: 'Order inside the column (design §4.2)', example: 1.5 })
  @IsNumber({ maxDecimalPlaces: AppConstant.Roadmap.RowOrderScale })
  @IsOptional()
  @Type(() => Number)
  rowOrder?: number;

  @ApiPropertyOptional({ description: 'ADD_NODE from the catalog, FILL_SLOT' })
  @IsInt()
  @Min(1)
  @IsOptional()
  @Type(() => Number)
  courseId?: number;

  @ApiPropertyOptional({ description: 'ADD_NODE of a course outside the catalog', maxLength: EntityConstant.CourseCode })
  @IsString()
  @IsOptional()
  @MaxLength(EntityConstant.CourseCode)
  customCode?: string;

  @ApiPropertyOptional({ maxLength: EntityConstant.LongString })
  @IsString()
  @IsOptional()
  @MaxLength(EntityConstant.LongString)
  customName?: string;

  @ApiPropertyOptional()
  @IsInt()
  @Min(0)
  @IsOptional()
  @Type(() => Number)
  customTheoryCredits?: number;

  @ApiPropertyOptional()
  @IsInt()
  @Min(0)
  @IsOptional()
  @Type(() => Number)
  customLabCredits?: number;

  @ApiPropertyOptional({ format: 'uuid', description: 'ADD_EDGE (new key), REMOVE_EDGE' })
  @IsUUID('4')
  @IsOptional()
  edgeKey?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'ADD_EDGE: A (taken first)' })
  @IsUUID('4')
  @IsOptional()
  sourceKey?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'ADD_EDGE: B (taken after)' })
  @IsUUID('4')
  @IsOptional()
  targetKey?: string;

  @ApiPropertyOptional({ enum: RelationTypeEnum, enumName: 'RelationType' })
  @IsEnum(RelationTypeEnum)
  @IsOptional()
  relationType?: RelationTypeEnum;

  @ApiPropertyOptional({ enum: CustomTermKindEnum, enumName: 'CustomTermKind', description: 'ADD_TERM' })
  @IsEnum(CustomTermKindEnum)
  @IsOptional()
  kind?: CustomTermKindEnum;

  @ApiPropertyOptional({ format: 'uuid', nullable: true, description: 'ADD_TERM / MOVE_TERM: insert after this term; empty = before the first term' })
  @IsUUID('4')
  @IsOptional()
  afterTermKey?: string | null;

  @ApiPropertyOptional({ maxLength: EntityConstant.TermLabel, description: 'ADD_TERM / UPDATE_TERM of a custom term' })
  @IsString()
  @IsOptional()
  @MaxLength(EntityConstant.TermLabel)
  label?: string;

  @ApiPropertyOptional({ nullable: true, description: 'UPDATE_TERM: 2025 = 2025-2026; null clears it', example: 2025 })
  @IsInt()
  @Min(AppConstant.AcademicYear.Min)
  @Max(AppConstant.AcademicYear.Max)
  @IsOptional()
  @Type(() => Number)
  academicYear?: number | null;

  @ApiPropertyOptional({ enum: TermInYearEnum, enumName: 'TermInYear', nullable: true })
  @IsEnum(TermInYearEnum)
  @IsOptional()
  termInYear?: TermInYearEnum | null;
}
