apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: iuroadmap

namePrefix: dev-

labels:
  - includeSelectors: true
    pairs:
      environment: development

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: "debug"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEBUG
          value: "true"

patches:
  - target:
      kind: Ingress
      name: iuroadmap-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.dev.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.dev.local

images:
  - name: gupjob/auth-service
    newTag: latest-dev
  - name: gupjob/admin-service
    newTag: latest-dev
  - name: gupjob/user-service
    newTag: latest-dev
  - name: gupjob/mentor-service
    newTag: latest-dev
  - name: gupjob/api-gateway
    newTag: latest-dev


